name: Reusable Build & Push

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL

      - name: Login to ACR
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.image_name }}:${{ github.sha }} ${{ inputs.service_path }}
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.image_name }}:${{ github.sha }}

      - name: Logout Azure
        if: always()
        run: az logout
