name: CD - Deploy Backend then Frontend

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    outputs:
      product_ip: ${{ steps.get_product_ip.outputs.external_ip }}
      order_ip: ${{ steps.get_order_ip.outputs.external_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Azure Login
        uses: azure/login@9d20a3e5b38e68d0cf58cf6329e2a3d734b3e5a1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group week08practicalrg --name week08practicalkubecls --overwrite-existing

      - name: Attach ACR
        run: az aks update --name week08practicalkubecls --resource-group week08practicalrg --attach-acr ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Deploy backend infra
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml

      - name: Deploy backend services
        run: |
          cd k8s/
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml

      - name: Get product IP
        id: get_product_ip
        run: echo "external_ip=$(kubectl get service product-service-w08e1 -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT

      - name: Get order IP
        id: get_order_ip
        run: echo "external_ip=$(kubectl get service order-service-w08e1 -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT

      - name: Logout Azure
        if: always()
        run: az logout

  deploy_frontend:
    runs-on: ubuntu-22.04
    needs: deploy_backend
    permissions:
      contents: read
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Azure Login
        uses: azure/login@9d20a3e5b38e68d0cf58cf6329e2a3d734b3e5a1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group week08practicalrg --name week08practicalkubecls --overwrite-existing

      - name: Inject backend IPs into frontend
        run: |
          sed -i "s|_PRODUCT_API_URL_|http://${{ needs.deploy_backend.outputs.product_ip }}:8000|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|http://${{ needs.deploy_backend.outputs.order_ip }}:8001|g" frontend/main.js

      - name: Build & Push frontend
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:${{ github.sha }}
          cd k8s/
          kubectl apply -f frontend.yaml

      - name: Logout Azure
        if: always()
        run: az logout
