name: CD - Deploy Backend then Frontend

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      aks_resource_group:
        description: "Resource group of the AKS cluster"
        required: true
        default: "week09rg"
      aks_cluster_name:
        description: "AKS cluster name"
        required: true
        default: "clusterweek09"

jobs:
  deploy_backend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    outputs:
      product_ip: ${{ steps.get_product_ip.outputs.external_ip }}
      order_ip: ${{ steps.get_order_ip.outputs.external_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group ${{ github.event.inputs.aks_resource_group }} --name ${{ github.event.inputs.aks_cluster_name }} --overwrite-existing

      - name: Attach ACR
        run: az aks update --name ${{ github.event.inputs.aks_cluster_name }} --resource-group ${{ github.event.inputs.aks_resource_group }} --attach-acr ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Deploy backend infra
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml

      - name: Deploy backend services
        run: |
          cd k8s/
          ku
